- name: Install nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv

- name: Install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
