---
- name: Add repository keys from key servers
  apt_key: id={{ item.id }} keyserver={{ item.keyserver }}
  with_items:
    - { id: '575159689BEFB442', keyserver: 'hkp://keyserver.ubuntu.com:80' }
    - { id: 'BBEBDCB318AD50EC6865090613B00F1FD2C19886', keyserver: 'hkp://keyserver.ubuntu.com:80' }

- name: Add repository keys from urls
  apt_key: url={{ item.url }}
  with_items:
    - { url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub' }

- name: Add repositories
  apt_repository: repo={{ item }}
  with_items:
    - 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    - 'deb http://download.fpcomplete.com/ubuntu xenial main'
    - 'deb http://repository.spotify.com stable non-free'
    - 'ppa:martin-frost/thoughtbot-rcm'
    - 'ppa:tmate.io/archive'

- name: Install packages
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - emacs
    - git
    - google-chrome-stable
    - postgresql
    - rcm
    - spotify-client
    - stack
    - tmate
    - tmux
    - vim
    - zsh
