---
- name: Install packages
  apt: pkg={{ item }} update_cache=yes
  with_items:
    # - libncurses5-dev
    # - postgresql-contrib
    - emacs
    - fonts-powerline
    - git
    - htop
    - libmysqlclient-dev
    - libpcre3-dev
    - libpq-dev
    - libsqlite3-dev
    - postgresql
    - silversearcher-ag
    - tmux
    - tree
    - xclip
    - zsh
  tags:
    - common

