---
- name: Clone zim
  git:
    repo: https://github.com/Eriner/zim.git
    dest: ~/.zim
    recursive: yes

- name: Symlink files
  file:
    src: "~/.zim/templates/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
  with_items:
    - zlogin
    - zshrc
